### ISSUE TITLE
Request to add license

### ISSUE THREAD

**Issue by Vuelos** [Yazir/godot-pinball#1]
Hi!
I'm interesed in use this repo for a personal project.

Can you specify what license you'd like to use?

here are some usefull links:
[Licenses dif.](https://choosealicense.com/)
[Github guide](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by Yazir** [comment]
license added, enjoy
